/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import classes.Cliente;
import classes.Funcionario;
import classes.Sorvete;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAOSorvete;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author loveo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //Componente de sorvete invisivel 
        lblSorvete.setVisible(false);
        lblValor.setVisible(false);
        jTextSorvete.setVisible(false);
        jTextValor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVisualizar = new javax.swing.JButton();
        jTextValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        jTextSorvete = new javax.swing.JTextField();
        lblSorvete = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jTextData = new javax.swing.JTextField();
        lbldata = new javax.swing.JLabel();
        jTextEnd = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFC = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVisualizar.setText("VISUALIZAR DADOS");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 150, 40));
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 90, 30));

        lblValor.setText("Valor:");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 40, -1));
        getContentPane().add(jTextSorvete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 110, 30));

        lblSorvete.setText("Sabor Sorvete: ");
        getContentPane().add(lblSorvete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 40));
        getContentPane().add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, 30));

        lbldata.setText("Data de Nascimento:");
        getContentPane().add(lbldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, 20));
        getContentPane().add(jTextEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 140, 30));

        lblEnd.setText("Endereço:");
        getContentPane().add(lblEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        getContentPane().add(jTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 140, 30));

        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 50, -1));

        jLabel4.setText("Cadastro da Sorveteria ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 130, 20));

        jComboBoxFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Cliente", "Sorvete" }));
        jComboBoxFC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFCItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Sorveteria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 230, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaPrincipal (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       //Informação dos componentes dadas pelo usuário
        String nome = jTextNome.getText();
        String endereco = jTextEnd.getText();
        String data = jTextData.getText(); 
        String tipo = jComboBoxFC.getSelectedItem().toString();
        String sabor = jTextSorvete.getText();
        
        
                if(tipo.equals("Funcionario")){
                    //Instanciar Classe Funcionario 
                    Funcionario f = new Funcionario();
                    f.setNome(nome);
                    f.setEndereco(endereco);
                    f.setData(data);
                    System.out.println(nome);
                    System.out.println(endereco);
                    System.out.println(data);
                    //Enviar os dados para a classe DAO para assim ser salvas no banco de dados 
                    DAOFuncionario daoFuncionario = new DAOFuncionario();
                         try {
                            daoFuncionario.salvarFuncionario(f);
                             } catch (SQLException ex) {
                                   Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                }else if(tipo.equals("Cliente")){
                    // Instanciar Classe Cliente
                    Cliente c = new Cliente();
                    c.setNome(nome);
                    c.setEndereco(endereco);
                    c.setData(data);
                 //Enviar os dados para a classe DAO para assim ser salvas no banco de dados 
                    DAOCliente daoCliente = new DAOCliente();
                         try {
                               daoCliente.salvarCliente(c);
                             } catch (SQLException ex) {
                                  Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                }else{
                    float valor = Float.parseFloat(jTextValor.getText());
                    //Instancia Sorvete
                    Sorvete sorvete = new  Sorvete();
                    sorvete.setSaborSorvete(sabor);
                    sorvete.setValorSorvete(valor);
                    
                    //Enviar dados para classe DAO para assim ser salvas no banco de dados 
                    
                    DAOSorvete  daos = new DAOSorvete();
                         try {
                             daos.salvarSorvete(sorvete);
                            } catch (SQLException ex) {
                          Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                         }
                    
                    
                  
                }
                
                //Limpando os campos da tela  
                jTextNome.setText(null);
                jTextEnd.setText(null);
                jTextData.setText(null);
                jTextSorvete.setText(null);
                jTextValor.setText(null);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxFCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFCItemStateChanged
        //Selecionar o item e conforme tornar alguns componentes invisiveis  
        String tipo = jComboBoxFC.getSelectedItem().toString();
         if(tipo.equals("Sorvete")){
             //Componente de Funcionario e Cliente fica invisivel 
                jTextNome.setVisible(false);
                jTextEnd.setVisible(false);
                jTextData.setVisible(false);
                lblNome.setVisible(false);
                lblEnd.setVisible(false);
                lbldata.setVisible(false);
                
                lblSorvete.setVisible(true);
                lblValor.setVisible(true);
                jTextSorvete.setVisible(true);
                jTextValor.setVisible(true);
                
         }else if(tipo.equals("Funcionario")){
                jTextNome.setVisible(true);
                jTextEnd.setVisible(true);
                jTextData.setVisible(true);
                lblNome.setVisible(true);
                lblEnd.setVisible(true);
                lbldata.setVisible(true);
                //Componente de sorvete fica invisivel 
                lblSorvete.setVisible(false);
                lblValor.setVisible(false);
                jTextSorvete.setVisible(false);
                jTextValor.setVisible(false);
         }else{
             jTextNome.setVisible(true);
                jTextEnd.setVisible(true);
                jTextData.setVisible(true);
                lblNome.setVisible(true);
                lblEnd.setVisible(true);
                lbldata.setVisible(true);
                //Componente de sorvete fica invisivel 
                lblSorvete.setVisible(false);
                lblValor.setVisible(false);
                jTextSorvete.setVisible(false);
                jTextValor.setVisible(false);
         }
    }//GEN-LAST:event_jComboBoxFCItemStateChanged

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        //Chama a outra tela de visualização 
        this.setVisible(false);
        new Visualizacao().setVisible(true);
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JComboBox<String> jComboBoxFC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextEnd;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSorvete;
    private javax.swing.JTextField jTextValor;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSorvete;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lbldata;
    // End of variables declaration//GEN-END:variables
}
