/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import classes.Cliente;
import classes.Funcionario;
import classes.Sorvete;
import dao.DAOCliente;
import dao.DAOFuncionario;
import dao.DAOSorvete;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author loveo
 */
public class Visualizacao extends javax.swing.JFrame {

    /**
     * Creates new form Visualizacao
     */
    public Visualizacao() {
        initComponents();
        //Inicializar as tabelas na tela 
          montarTabela();
          montarTabelaFuncionario();
          montarTabelaSorvete();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        lblFuncionario = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSorvete = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        lblSorvete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 30));

        lblFuncionario.setText("Funcionario:");
        getContentPane().add(lblFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 70, 20));

        lblCliente.setText("Cliente:");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, -1));

        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 390, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Visualização de Dados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 240, 170));

        jScrollPane2.setViewportView(jTableSorvete);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 390, 80));

        jScrollPane3.setViewportView(jTableFuncionario);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 390, 80));

        lblSorvete.setText("Sorvete");
        getContentPane().add(lblSorvete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaPrincipal (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -170, 1380, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // Voltar para tela inicial 
        this.setVisible(false);
        new Principal().setVisible(true);
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed
     private void montarTabela(){
        //Dados para a montagem das Colunas
        String colunas[] = new String[]{"Id","Nome","Endereço","Data de aniversario"};
        //Criacao do objeto que define o modelo da Tabela
        //Passamos null no primeiro argumento, pois as linhas serão definidas
        //Dentro do foreach. Ele recebe como argumento um vetor de Objetos
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        //Criação do objeto DAOCliente para recuperar os dados dos clientes
        //que estão na Tabela Cliente
         DAOCliente cliente = new DAOCliente();
        //Chamada do método que retorna todos os clientes cadastrados
        //na tabela Cliente
        ArrayList<Cliente> Lista = cliente.retornarCliente();
        //ForEach que pega cada objeto cliente da Lista e atribui
        //ao objeto Cliente a
       for(Cliente a : Lista){
            //Nesta linha nos adicionamos as linhas na tabela
            //Montamos aqui um Vetor de Objetos
            modelotabela.addRow(new Object[]{a.getIdCliente(), a.getNome(),a.getEndereco(), a.getData()});    
        }
     jTableCliente.setModel(modelotabela);     
    }
     
      private void montarTabelaFuncionario(){
        //Dados para a montagem das Colunas
        String colunas[] = new String[]{"Id","Nome","Endereço","Data de aniversario"};
        //Criacao do objeto que define o modelo da Tabela
        //Passamos null no primeiro argumento, pois as linhas serão definidas
        //Dentro do foreach. Ele recebe como argumento um vetor de Objetos
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        //Criação do objeto DAOFuncionario para recuperar os dados dos clientes
        //que estão na Tabela Funcionario
          DAOFuncionario funcionario = new DAOFuncionario();
        //Chamada do método que retorna todos os clientes cadastrados
        //na tabela Funcionario
        ArrayList<Funcionario> Lista = funcionario.retornarFuncionario();
        //ForEach que pega cada objeto Funcionario da ListaA e atribui
        //ao objeto Funcionario a
       for(Funcionario a : Lista){
            //Nesta linha nos adicionamos as linhas na tabela
            //Montamos aqui um Vetor de Objetos
            modelotabela.addRow(new Object[]{a.getIdFuncionario(), a.getNome(),a.getEndereco(), a.getData()});    
        }
     jTableFuncionario.setModel(modelotabela);     
    }
     
      
    private void montarTabelaSorvete(){
        //Dados para a montagem das Colunas
        String colunas[] = new String[]{"Id","Sabor","Valor do Sorvete"};
        //Criacao do objeto que define o modelo da Tabela
        //Passamos null no primeiro argumento, pois as linhas serão definidas
        //Dentro do foreach. Ele recebe como argumento um vetor de Objetos
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        //Criação do objeto DAOSorvete para recuperar os dados dos sorveetes
        //que estão na Tabela Sorvetes
         DAOSorvete sorvete = new DAOSorvete();
        //Chamada do método que retorna todos os clientes cadastrados
        //na tabela Sorvete
        ArrayList<Sorvete> Lista = sorvete.retornarSorvete();
        //ForEach que pega cada objeto sorvete da Lista A e atribui
        //ao objeto Sorvete a
       for(Sorvete a : Lista){
            //Nesta linha nos adicionamos as linhas na tabela
            //Montamos aqui um Vetor de Objetos
            modelotabela.addRow(new Object[]{a.getIdSorvete(), a.getSaborSorvete(),a.getValorSorvete()});    
        }
     jTableSorvete.setModel(modelotabela);     
    }  
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableFuncionario;
    private javax.swing.JTable jTableSorvete;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblSorvete;
    // End of variables declaration//GEN-END:variables
}
